# Generated by Django 3.2.13 on 2022-06-20 14:56

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_customuser_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('ext_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the resource.', max_length=255, verbose_name='title')),
                ('description', core.fields.CustomSmallTextField(blank=True, help_text='A basic description of the resource.', max_length=2048, null=True, verbose_name='description')),
                ('created_at_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('modified_at_time', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('current_major_version', models.IntegerField(default=0, editable=False, verbose_name='major_version')),
                ('current_minor_version', models.IntegerField(default=0, editable=False, verbose_name='minor_version')),
                ('current_revision_number', models.IntegerField(default=0, editable=False, verbose_name='revision number')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='1.0', max_length=25, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='english', help_text='Please provide the langauge of the Terms of Use document.', max_length=100, null=True)),
                ('contributors', models.ManyToManyField(blank=True, help_text='contributors_help', related_name='termsofuse_contributor', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(help_text='creator_help', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termsofuse_creator', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(help_text='modifier_help', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termsofuse_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms of Use',
                'verbose_name_plural': 'Terms of Use',
                'ordering': ['-created_at_time'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfUseUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.termsofuse')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='TermsOfUseGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.termsofuse')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
                'unique_together': {('group', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='TermsOfUseAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at_time', models.DateTimeField(auto_now=True)),
                ('tou_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_tou_versions', to='users.termsofuse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accepted TOU',
                'verbose_name_plural': 'Accepted TOUs',
                'ordering': ('user',),
                'unique_together': {('tou_version', 'user')},
            },
        ),
    ]
