# Generated by Django 3.2.13 on 2022-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_termsofuse_termsofuseaccepted_termsofusegroupobjectpermission_termsofuseuserobjectpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_tou_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
