# Generated by Django 3.2.14 on 2022-07-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofuse',
            name='current_major_version',
        ),
        migrations.RemoveField(
            model_name='termsofuse',
            name='current_minor_version',
        ),
        migrations.RemoveField(
            model_name='termsofuse',
            name='current_revision_number',
        ),
    ]
